name: Demo of stackql-exec

on:
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  stackql-exec-job:
    name: stackql-exec-job
    runs-on: ubuntu-latest
    env: {}

    steps:
      - uses: actions/checkout@v3
        name: "[SETUP] checkout repo"
        with:
          fetch-depth: 0

      - name: prep Google creds
        env: 
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        shell: bash
        run: | ## use the base64 encoded secret to create json file
          sudo echo $GOOGLE_CREDS > sa-key.json    

      - name: setup StackQL
        uses: stackql/setup-stackql@v1.1.0

      - name: pull Google docs
        uses: stackql/stackql-exec@v1.0.1
        with:
          auth_obj_path: stackql/auth.json
          query: "REGISTRY PULL google"

      - name: dry run StackQL query
        shell: bash
        run: |
          stackql exec -i ./stackql/scripts/deploy-instances.iql --output text -H --dryrun

      - name: deploy instances using stackql
        uses: stackql/stackql-exec@v1.0.1
        with:
          auth_obj_path: './stackql/auth.json'
          query_file_path: './stackql/scripts/deploy-instances.iql'

      - name: stop running instances using stackql
        uses: stackql/stackql-exec@v1.0.1
        with:
          auth_obj_path: './stackql/auth.json'
          query_file_path: './stackql/scripts/stop-instances.iql'